train_ratio: 0.8
batch_size: 4
num_epochs: 16
optimizer: "adam"
learning_rate: 1e-4
image_scale: 0.5   # 1.0 = full, 0.5 = half size

wandb:
  use_wandb: true
  project: "bc-thesis"
  run_name: "tvrdsia-loss" # auto
  log_interval: 1 # every N epoch

debug: false