_wandb:
    value:
        cli_version: 0.23.1
        e:
            6ft70rp4z37x9jzwugogdvmr2miv25dd:
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 16
                cpu_count_logical: 32
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "115590033408"
                        used: "16158556160"
                email: xmajercik@stuba.sk
                executable: /home/majercikt/.conda/envs/bc-thesis/bin/python
                git:
                    commit: c2a2bdc3255889c66a9e73868c5c33e8a7967f32
                    remote: https://github.com/tomasmajercik/bc-thesis.git
                gpu: NVIDIA GeForce RTX 3090
                gpu_count: 2
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10496
                      memoryTotal: "25769803776"
                      name: NVIDIA GeForce RTX 3090
                      uuid: GPU-64769a18-704f-9b0b-eaef-23ad2d9d4d74
                    - architecture: Ampere
                      cudaCores: 10496
                      memoryTotal: "25769803776"
                      name: NVIDIA GeForce RTX 3090
                      uuid: GPU-b0b770ab-6704-bf12-2003-33c3b8d0c670
                host: beast1
                memory:
                    total: "168618426368"
                os: Linux-6.8.0-90-generic-x86_64-with-glibc2.35
                program: /home/majercikt/projects/bc-thesis/train.py
                python: CPython 3.12.12
                root: /home/majercikt/projects/bc-thesis
                startedAt: "2026-02-12T21:40:10.348558Z"
                writerId: 6ft70rp4z37x9jzwugogdvmr2miv25dd
        m: []
        python_version: 3.12.12
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 16
            "4": 3.12.12
            "5": 0.23.1
            "12": 0.23.1
            "13": linux-x86_64
batch_size:
    value: 2
learning_rate:
    value: "1e-4"
num_epochs:
    value: 10
optimizer:
    value: adam
train_ratio:
    value: 0.8
wandb:
    value:
        log_interval: 1
        project: multi_encoder_unet
        run_name: null
        use_wandb: true
